#!/usr/bin/env perl

use strict;
use warnings;

use FindBin;
BEGIN { unshift @INC, "$FindBin::Bin/../lib", "$FindBin::Bin/../local/lib/perl5" }
use Mojolicious::Commands;

# Start command line interface for application
Mojolicious::Commands->start_app('KidBank');
